name: publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Build Docker Image

      - name: Login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.WORDPRES_TOKEN }}

      - name: Build the tenant-rabbit Docker image
        run: |
            docker-compose -f docker-compose.yml up -d
            docker tag wordpress ghcr.io/cristiandimas/wordpress:latest  
            docker push ghcr.io/cristiandimas/wordpress:latest

  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Oracle Cloud
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DIGITAL_HOST }}
          username: ${{ secrets.DIGITAL_USERNAME }}
          key: ${{ secrets.DIGITAL_PRIVATE_KEY }}
          port: ${{ secrets.DIGITAL_PORT }}
          script: |
            script: |
            # Pull the latest Docker image
            docker pull ghcr.io/cristiandimas/wordpress:latest
            
            # Deploy the Docker image to Oracle Cloud
            docker run -d --name wordpress -p 80:80 ghcr.io/cristiandimas/wordpress:latest


               
  

