# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup SSH
      # You may pin to the exact commit or the version.
      # uses: kielabokkie/ssh-key-and-known-hosts-action@5b675129e6aa73a496c939eb1f4a9fe4502fc324
        uses: kielabokkie/ssh-key-and-known-hosts-action@master
        with:
        # Private key required to access the host
           ssh-private-key: ${secrets.DIGITAL_PRIVATE_KEY}
           # Hostname or IP to add to the known hosts file
           ssh-host: ${secrets.DIGITAL_HOST}
            # Port for key-scanning the server
           ssh-port:  ${secrets.DIGITAL_PORT}

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install docker-ce

      - name: Build and push Docker images
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wordpress-nginx .
          docker push ${{ secrets.DOCKER_USERNAME }}/wordpress-nginx
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wordpress-php-fpm .
          docker push ${{ secrets.DOCKER_USERNAME }}/wordpress-php-fpm
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wordpress-db .
          docker push ${{ secrets.DOCKER_USERNAME }}/wordpress-db
         
          


