name: publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Build Docker Image

      - name: Login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.WORDPRES_TOKEN }}

      - name: Build the tenant-rabbit Docker image
        run: 
          docker-compose -f docker-compose.yml up -d --tag ghcr.io/cristiandimas/wordpress:latest  
          docker push ghcr.io/cristiandimas/wordpress:latest

  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest
    steps:      
      - name: Install sshpass
        run: 
          sudo apt-get install -y sshpass

      - name: SSH into Server
        run: 
          sshpass -p ${{ secrets.DIGITAL_PRIVATE_KEY }} ssh -o StrictHostKeyChecking=no ${{ secrets.DIGITAL_USERNAME }}@${{ secrets.DIGITAL_HOST }}    
          docker-compose -f docker-compose.yml up -d 


